import type { RecommendationResponse } from "@/lib/types";

const CONFIDENCE_STYLES: Record<string, string> = {
  high: "bg-leaf-100 text-leaf-700",
  medium: "bg-wheat/20 text-soil-700",
  low: "bg-alert/10 text-alert",
};

export default function RecommendationResults({
  data,
}: {
  data: RecommendationResponse;
}) {
  return (
    <section
      aria-labelledby="results-heading"
      className="space-y-6"
      data-testid="recommendation-results"
    >
      <h2 id="results-heading" className="font-display text-2xl text-soil-900">
        Recommended crops for {data.location}, {data.season} season
      </h2>

      {data.uncertaintyNote && (
        <p
          role="status"
          className="rounded-md border border-wheat/40 bg-wheat/10 px-4 py-3 text-sm text-soil-700"
        >
          <span className="font-semibold">Note:</span> {data.uncertaintyNote}
        </p>
      )}

      <ol className="space-y-4">
        {data.crops.map((crop, i) => (
          <li
            key={crop.name + i}
            className="rounded-lg border border-soil-200 bg-white p-5"
          >
            <div className="flex items-start justify-between gap-3">
              <h3 className="font-display text-lg text-soil-900">
                {i + 1}. {crop.name}
              </h3>
              <span
                className={`shrink-0 rounded-full px-3 py-1 font-mono text-xs uppercase tracking-wide ${
                  CONFIDENCE_STYLES[crop.confidence] ?? CONFIDENCE_STYLES.medium
                }`}
              >
                {crop.confidence} confidence
              </span>
            </div>

            <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-soil-700">
              {crop.reasons.map((reason, idx) => (
                <li key={idx}>{reason}</li>
              ))}
            </ul>

            {crop.precautions.length > 0 && (
              <div className="mt-3 border-t border-soil-100 pt-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-soil-500">
                  Precautions
                </p>
                <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-soil-600">
                  {crop.precautions.map((p, idx) => (
                    <li key={idx}>{p}</li>
                  ))}
                </ul>
              </div>
            )}
          </li>
        ))}
      </ol>

      {data.generalNotes.length > 0 && (
        <div className="rounded-lg bg-soil-100 p-5">
          <h3 className="font-display text-base text-soil-900">
            General notes
          </h3>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-soil-700">
            {data.generalNotes.map((note, idx) => (
              <li key={idx}>{note}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="text-xs text-soil-400">
        This is general agronomic guidance generated by an AI model, not a
        substitute for advice from your local agricultural extension office.
      </p>
    </section>
  );
}
